const { extractInlineModule, readRepositoryFile, collectNamedNodes, nodeText } = require('./test-support.cjs');
const source = extractInlineModule();
const pricingSource = readRepositoryFile('js/domain/pricing.mjs');
const pricingNames = ['parseMoney', 'getNumericPrice', 'getSinglePrice', 'computePackageMargins'];
const authorizationSource = readRepositoryFile('js/domain/authorization.mjs');
const authorizationNames = ['ROLE_LABELS', 'NO_PERMISSIONS', 'ROLE_PERMISSIONS', 'isValidRole', 'isActiveProfile', 'getProfilePermissions'];
const retailerSource = readRepositoryFile('js/domain/retailers.mjs');
const retailerNames = ['normalizeRetailerName', 'RETAILER_FIELDS', 'RETAILER_AUTOCOMPLETE', 'retailerLocation', 'normalizeRetailerSearch', 'retailerSearch', 'validRetailerId', 'formatRetailerPhone', 'validateRetailer', 'findDuplicateRetailer'];
const territorySource = readRepositoryFile('js/domain/territories.mjs');
const territoryNames = ['territoryDisplay', 'normalizeTerritory', 'retailerTerritoryLabel', 'retailerTerritoryFields', 'retailerTerritoryOptions', 'filterRetailerTerritories', 'territoryMismatches'];
const assignmentSource = readRepositoryFile('js/domain/assignments.mjs');
const assignmentNames = ['retailerAssignments', 'isAssignableRetailerUser', 'validateRepAssignments', 'assignedRepLabel', 'assignmentSummary', 'filterRetailerAssignments'];
const savedOrderSource = readRepositoryFile('js/domain/saved-orders.mjs');
const savedOrderNames = ['nonnegativeMoney', 'isReadableSavedOrder', 'buildSavedOrder', 'buildReorderPlan', 'mergeReorderItems'];
const catalogSource = readRepositoryFile('js/domain/catalog-data.mjs');
const catalogNames = ['newSizeRow', 'SEED_CIGARS', 'EMPTY_FORM', 'PACK_OPTIONS'];
const names = ['ROLE_LABELS', 'NO_PERMISSIONS', 'ROLE_PERMISSIONS', 'isValidRole', 'isActiveProfile', 'getProfilePermissions', 'normalizeRetailerName', 'nonnegativeMoney', 'PACK_OPTIONS', 'SEED_CIGARS', 'parseMoney', 'getNumericPrice', 'getSinglePrice', 'validRetailerId', 'buildSavedOrder', 'isReadableSavedOrder', 'buildReorderPlan', 'mergeReorderItems', 'RETAILER_FIELDS', 'RETAILER_AUTOCOMPLETE', 'territoryDisplay', 'normalizeTerritory', 'retailerTerritoryLabel', 'retailerTerritoryFields', 'retailerTerritoryOptions', 'filterRetailerTerritories', 'territoryMismatches', 'retailerAssignments', 'isAssignableRetailerUser', 'validateRepAssignments', 'assignedRepLabel', 'assignmentSummary', 'filterRetailerAssignments', 'useAssignmentProfiles', 'formatRetailerPhone', 'RetailerPhoneInput', 'validateRetailer', 'findDuplicateRetailer', 'retailerLocation', 'normalizeRetailerSearch', 'RetailerLocation', 'retailerSearch', 'hasMeaningfulDraft', 'retailerOrderFields'];
const nodes = collectNamedNodes(source, (name) => names.includes(name));
const pricingNodes = collectNamedNodes(pricingSource, (name) => pricingNames.includes(name));
const authorizationNodes = collectNamedNodes(authorizationSource, (name) => authorizationNames.includes(name));
const retailerNodes = collectNamedNodes(retailerSource, (name) => retailerNames.includes(name));
const territoryNodes = collectNamedNodes(territorySource, (name) => territoryNames.includes(name));
const assignmentNodes = collectNamedNodes(assignmentSource, (name) => assignmentNames.includes(name));
const savedOrderNodes = collectNamedNodes(savedOrderSource, (name) => savedOrderNames.includes(name));
const catalogNodes = collectNamedNodes(catalogSource, (name) => catalogNames.includes(name));
exports.loadClient = (environment = {}) => {
  const code = names.map((name) => {
    const module = [[pricingNodes, pricingSource], [authorizationNodes, authorizationSource], [retailerNodes, retailerSource], [territoryNodes, territorySource], [assignmentNodes, assignmentSource], [savedOrderNodes, savedOrderSource], [catalogNodes, catalogSource]].find(([sourceNodes]) => sourceNodes.has(name));
    const [sourceNodes, declarationSource] = module || [nodes, source];
    const node = sourceNodes.get(name); if (!node) throw new Error('Missing client helper: ' + name);
    const body = nodeText(declarationSource, sourceNodes, name);
    return node.type === 'FunctionDeclaration' ? body : `const ${name} = ${body};`;
  }).join('\n');
  return Function(...Object.keys(environment), code + '\nreturn {' + names.join(',') + '};')(...Object.values(environment));
};
