export const newSizeRow = () => ({
  key: `s-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
  vitola: "", dims: "", msrp: "",
  keystoneSingle: "", keystoneBox10: "", keystoneBox20: "", keystoneBundle20: "",
});

export const SEED_CIGARS = [
  {
    id: "1982",
    name: "1982",
    line: "Core Line",
    imageUrl: "",
    wrapper: "Connecticut Shade",
    binder: "Dominican (Cuban-seed)",
    filler: "Dominican",
    origin: "",
    strength: 1,
    body: 1,
    tastingNotes: [],
    pairings: [],
    sizes: [
      { key: "1982-robusto", vitola: "Robusto", dims: "50 x 5", msrp: "$12.40", keystoneSingle: "$6.45 box / $6.20 bundle", keystoneBox10: "$64.50", keystoneBox20: "$129.00", keystoneBundle20: "$124.00" },
      { key: "1982-toro", vitola: "Toro", dims: "52 x 6", msrp: "$13.00", keystoneSingle: "$6.50 box / $6.25 bundle", keystoneBox10: "$65.00", keystoneBox20: "$130.00", keystoneBundle20: "$125.00" },
    ],
    notes: "Mild-bodied, our highest recommendation per brand copy. No specific flavor notes on file — confirm with tasting panel.",
  },
  {
    id: "1996",
    name: "1996",
    line: "Core Line",
    imageUrl: "",
    wrapper: "Connecticut Shade / San Andrés Maduro (\"barber pole\")",
    binder: "Dominican (Cuban-seed)",
    filler: "Dominican",
    origin: "",
    strength: 2,
    body: 2,
    tastingNotes: [],
    pairings: [],
    sizes: [
      { key: "1996-robusto", vitola: "Robusto", dims: "50 x 5", msrp: "$12.40", keystoneSingle: "$6.45 box / $6.20 bundle", keystoneBox10: "$64.50", keystoneBox20: "$129.00", keystoneBundle20: "$124.00" },
      { key: "1996-toro", vitola: "Toro", dims: "52 x 6", msrp: "$13.00", keystoneSingle: "$6.65 box / $6.40 bundle", keystoneBox10: "$67.50", keystoneBox20: "$135.00", keystoneBundle20: "$130.00" },
    ],
    notes: "Light-to-medium blend, double-wrapper \"barber pole\" construction.",
  },
  {
    id: "haze-gray-sugartip",
    name: "Haze Gray (Sugar Tip)",
    line: "Core Line",
    imageUrl: "",
    wrapper: "Ecuadorian Sumatra",
    binder: "Dominican",
    filler: "Dominican",
    origin: "",
    strength: 2,
    body: 2,
    tastingNotes: ["Sweet", "Sugar-tip finish"],
    pairings: [],
    sizes: [
      { key: "sugartip-robusto", vitola: "Robusto", dims: "50 x 5", msrp: "$12.40", keystoneSingle: "$6.45 box / $6.20 bundle", keystoneBox10: "$64.50", keystoneBox20: "$129.00", keystoneBundle20: "$124.00" },
    ],
    notes: "\"Smooth and sweet experience\" per brand copy — sugar tip adds extra sweetness. Strength/body estimated (mild-medium); confirm exact rating.",
  },
  {
    id: "backpack-infused",
    name: "The Backpack (Infused)",
    line: "Core Line",
    imageUrl: "",
    wrapper: "San Andrés Maduro",
    binder: "Nicaraguan",
    filler: "Dominican & Nicaraguan",
    origin: "",
    strength: 2,
    body: 2,
    tastingNotes: ["Chocolate"],
    pairings: [],
    sizes: [
      { key: "backpack-robusto", vitola: "Robusto", dims: "50 x 5", msrp: "$12.40", keystoneSingle: "$6.45 box / $6.20 bundle", keystoneBox10: "$64.50", keystoneBox20: "$129.00", keystoneBundle20: "$124.00" },
    ],
    notes: "Infused cigar — \"luscious and flavorful burst of chocolate.\" Strength/body estimated; confirm exact rating.",
  },
  {
    id: "patriot",
    name: "The Patriot",
    line: "",
    imageUrl: "",
    wrapper: "Double Maduro Nicaraguan",
    binder: "Nicaraguan",
    filler: "Nicaraguan (well-aged)",
    origin: "",
    strength: 3,
    body: 3,
    tastingNotes: ["Robust", "Smooth finish"],
    pairings: [],
    sizes: [
      { key: "patriot-toro", vitola: "Toro", dims: "52 x 6", msrp: "$13.00", keystoneSingle: "$6.65 box / $6.40 bundle", keystoneBox10: "$66.50", keystoneBox20: "$133.00", keystoneBundle20: "$128.00" },
    ],
    notes: "★ 95 rating, Stogie Press. A portion of every sale supports Operation Zero (veteran suicide prevention). Medium-bodied, boldest expression of Haze Gray's \"vets helping vets\" mission.",
  },
  {
    id: "admiral",
    name: "The Admiral",
    line: "",
    imageUrl: "",
    wrapper: "Nicaraguan Habano (triple-capped)",
    binder: "Nicaraguan (Cuban-seed)",
    filler: "Nicaraguan",
    origin: "",
    strength: 3,
    body: 3,
    tastingNotes: [],
    pairings: [],
    sizes: [
      { key: "admiral-robusto", vitola: "Robusto", dims: "50 x 5", msrp: "$12.40", keystoneSingle: "$6.45 box / $6.20 bundle", keystoneBox10: "$64.50", keystoneBox20: "$129.00", keystoneBundle20: "$124.00" },
      { key: "admiral-toro", vitola: "Toro", dims: "52 x 6", msrp: "$13.00", keystoneSingle: "$6.65 box / $6.40 bundle", keystoneBox10: "$66.50", keystoneBox20: "$133.00", keystoneBundle20: "$128.00" },
    ],
    notes: "Medium-bodied.",
  },
  {
    id: "brotherhood",
    name: "The Brotherhood",
    line: "War Dogs Core Line",
    imageUrl: "",
    wrapper: "Brazilian Maduro",
    binder: "Dominican",
    filler: "Dominican, Honduran, Nicaraguan (ligero trio)",
    origin: "",
    strength: 5,
    body: 5,
    tastingNotes: ["Spicy", "Reminiscent of vintage Cuban cigars"],
    pairings: [],
    sizes: [
      { key: "brotherhood-robusto", vitola: "Robusto", dims: "50 x 5", msrp: "$12.40", keystoneSingle: "$6.45 box / $6.20 bundle", keystoneBox10: "$64.50", keystoneBox20: "$129.00", keystoneBundle20: "$124.00" },
      { key: "brotherhood-toro", vitola: "Toro", dims: "52 x 6", msrp: "$13.00", keystoneSingle: "$6.65 box / $6.40 bundle", keystoneBox10: "$66.50", keystoneBox20: "$133.00", keystoneBundle20: "$128.00" },
    ],
    notes: "First release of the War Dogs Core Line. Full-body, very spicy smoke.",
  },
  {
    id: "irmaos-do-mar",
    name: "Irmãos do Mar",
    line: "",
    imageUrl: "",
    wrapper: "Brazilian Arapiraca",
    binder: "Madeira, Portugal",
    filler: "Zimbabwe/Africa, Canary Islands/Spain, Estelí/Nicaragua",
    origin: "",
    strength: 4,
    body: 4,
    tastingNotes: ["Rich", "Complex", "Smooth herbal backbone", "Peppery finish"],
    pairings: [],
    sizes: [
      { key: "irmaos-toro", vitola: "Toro", dims: "54 x 6", msrp: "$15.00", keystoneSingle: "$7.50 box / $7.25 bundle", keystoneBox10: "$75.00", keystoneBox20: "$150.00", keystoneBundle20: "$145.00" },
    ],
    notes: "★ 98 rating, Momento Cigars (Clint Aaron review). Medium-to-full bodied, exotic tobaccos from five nations, excellent burn.",
  },
  {
    id: "bussola",
    name: "The Bussola",
    line: "",
    imageUrl: "",
    wrapper: "Arapiraca Oscuro",
    binder: "Olar Dominicano",
    filler: "Ligero piloto, Cubano, Visio San Vicente, Ligero PA, Seco Olar Dominicano & Indonesian",
    origin: "",
    strength: 4,
    body: 4,
    tastingNotes: ["Espresso", "Dark earth", "Spice", "Cocoa"],
    pairings: [],
    sizes: [
      { key: "bussola-toro", vitola: "Toro", dims: "54 x 6", msrp: "$15.00", keystoneSingle: "$7.50 box / $7.25 bundle", keystoneBox10: "$75.00", keystoneBox20: "$150.00", keystoneBundle20: "$145.00" },
    ],
    notes: "Medium-full to full-bodied, bold and balanced.",
  },
];

export const EMPTY_FORM = {
  name: "", line: "", imageUrl: "", wrapper: "", binder: "", filler: "",
  origin: "", strength: 3, body: 3,
  tastingNotes: "", pairings: "", notes: "",
  sizes: [newSizeRow()],
};

export const PACK_OPTIONS = [
{
  key: "single",
  label: "Single (loose stick)"
},
{
  key: "box10",
  label: "10ct Box"
},
{
  key: "box20",
  label: "20ct Box"
},
{
  key: "bundle20",
  label: "20ct Bundle"
  }
];
